import type { Metadata } from "next";
import "../css/globals.css";
import 'swiper/css';
import 'swiper/css/pagination';
import 'leaflet/dist/leaflet.css';
import 'leaflet/dist/images/marker-icon.png'
import 'leaflet/dist/leaflet.css'
import { interFont } from "@/utils/font";
import { ProviderNextUI } from "@/lib/nextProvider";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  icons: {
    icon: "https://pengaduan-web.vercel.app/logo.svg"
  },
  title: "YADIKA SMART APP",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body suppressHydrationWarning={true} >
        <ProviderNextUI>
          <Toaster position="top-center"
            reverseOrder={false} />
          <div className={` ${interFont.className} dark:bg-boxdark-2 dark:text-bodydark`}>
            {children}
          </div>
        </ProviderNextUI>
      </body>
    </html>

  );
}
